server:
   port: 8081
   
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/creditcard
    username: sa
    password:
    driverClassName: org.h2.Driver